# Generated by Django 2.0.5 on 2018-08-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180825_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[(0, 'Refill'), (1, 'Rx'), (2, 'OTC'), (3, 'Rx/OTC')], default=0, max_length=255, verbose_name='Type of the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_processor',
            field=models.CharField(choices=[(0, 'Stripe'), (1, 'Braintree'), (2, 'Square')], default=0, max_length=16, verbose_name='Payment Processor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Checkout Initiated'), (2, 'Checkout Shipping Address Completed'), (3, 'Checkout Payment Authorized'), (4, 'Checkout Payment Captured'), (5, 'Checkout Payment Declined'), (6, 'Medical Visit Eligibility Verified'), (7, 'Medical Visit Ineligible'), (8, 'Medical Visit Terms Accepted'), (9, 'Medical Visit Questionnaire Completed'), (10, 'Medical Visit Photos Uploaded'), (11, 'Medical Visit Provider Pending'), (12, 'Medical Visit Provider Awaiting User Input'), (13, 'Medical Visit Provider Rx Submitted'), (14, 'Medical Visit Provider Rx Denied'), (15, 'Medical Visit Provider Cancelled'), (16, 'Pharmacy Rx Received'), (17, 'Pharmacy Rx Fulfilled'), (18, 'Pharmacy Rx Shipped'), (19, 'Pharmacy Rx Error'), (20, 'Shipped'), (21, 'Picked Up'), (22, 'Cancelled'), (23, 'Refunded'), (24, 'Disputed'), (25, 'Manual Verification Required')], default=0, max_length=32, verbose_name='Order status'),
        ),
    ]
